댓글 수정
TIL-Log-lab/Tilog-server-node-v2 pull request #55
Opened 2022-04-24 06:01 UTC by Daphne-dev

# 구현 개요

댓글 수정 엔드포인트 구현

## 작업 사항

- PUT : /comments
    - 댓글 수정 Repository 추가
    - 댓글 수정 Service, DTO 추가
    - 댓글 수정 Controller 추가
 
## 이슈 트래커 번호

resolve #54

2022-04-26 02:43 UTC, argon1025 commented on src/comments/comments.service.ts
> +
댓글은 존재하지만 유저 아이디가 일치하지 않아서 권한이 없는 상태인 경우엔
따로 권한 에러를 뿌려주는게 어떤가요?

2022-04-26 02:44 UTC, argon1025 requested changes
확인 부탁드려요!

2022-04-26 02:48 UTC, MINJE-98 approved these changes
확인했습니다.

2022-04-26 05:48 UTC, Daphne-dev commented
> 확인 부탁드려요!

요청사항 반영되었습니다. 확인 부탁드려요

2022-04-27 07:00 UTC, argon1025 approved these changes
좋습니다!

2022-04-27 07:01 UTC, merged