Feature/62
TIL-Log-lab/Tilog-server-node-v2 pull request #68
Opened 2022-05-02 05:06 UTC by argon1025

# 💫 PR

#### 이슈 트래커 번호
resolve #62 

---

## 1.작업 세부내역

- 통일되지 않은 리턴타입을 통일했습니다
- Swagger OpenAPI에서 header user-agent가 필수값이던 문제를 해결했습니다
- 쿠키 타입, 메서드명을 명확한 의도를 가지도록 변경했습니다
- 쿠키를 생성하는 로직을 분리했습니다
- 쿠키가 빈 문자열인 경우를 체크하는 로직을 추가했습니다

## 3.Merge 이후 조치
- [ ] OpenAPI 배포

2022-05-02 05:31 UTC, Daphne-dev requested changes
확인부탁드려요 ~

2022-05-02 05:31 UTC, Daphne-dev commented on src/users/users.service.ts
> +import { UpSertUserAndGetIdResponse } from '@api/users/type/users.service.type';
UpSertUser -> UpsertUser 로 이름을 변경하는게 어떨까요

2022-05-05 12:58 UTC, argon1025 commented on src/users/users.service.ts
> +import { UpSertUserAndGetIdResponse } from '@api/users/type/users.service.type';
좋습니다!

2022-05-05 12:59 UTC, argon1025 commented
@Daphne-dev 
OpenAPI 배포를위해 리뷰사항 반영 후 관리자 권한으로 병합했습니다
시간나실때 마지막 체킹 부탁해요!

2022-05-05 12:59 UTC, merged